# python用自動保管システム
[[plugins]]
repo = 'zchee/deoplete-jedi'

# linter 実行プラグイン
[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python', 'html', 'css', 'javascript']
hook_source = '''
	source ~/.dotfiles/vim/rc/toml/plugins/ale.vim
'''
